name: Update Appcast

on:
  release:
    types: [published]

jobs:
  update-appcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Generate appcast entry
        id: appcast
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          DMG_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/Nook-${VERSION}.dmg"
          DATE=$(date -R)

          # Sanitize short version (remove v if present)
          SHORT_VERSION=${VERSION#v}

          ENTRY=$(cat <<EOF
          <item>
              <title>Version ${SHORT_VERSION}</title>
              <sparkle:releaseNotesLink>https://github.com/${{ github.repository }}/releases/tag/${VERSION}</sparkle:releaseNotesLink>
              <pubDate>${DATE}</pubDate>
              <enclosure
                  url="${DMG_URL}"
                  sparkle:version="${SHORT_VERSION//[^0-9]/}"
                  sparkle:shortVersionString="${SHORT_VERSION}"
                  type="application/x-apple-diskimage"/>
          </item>
          EOF
          )

          # Insert entry before closing </channel>
          awk -v entry="$ENTRY" '/<\/channel>/{print entry RS $0; next}1' appcast.xml > appcast-new.xml
          mv appcast-new.xml appcast.xml

      - name: Commit and push update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add appcast.xml
          git commit -m "Auto-update appcast for release ${{ github.event.release.tag_name }}"
          git push origin gh-pages
